// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: rio.proto

package rio_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPIOselected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GPIOLineOffset int32  `protobuf:"varint,1,opt,name=GPIOLineOffset,proto3" json:"GPIOLineOffset,omitempty"`
	GPIOLineValue  int32  `protobuf:"varint,2,opt,name=GPIOLineValue,proto3" json:"GPIOLineValue,omitempty"`
	GPIOLineAlias  string `protobuf:"bytes,3,opt,name=GPIOLineAlias,proto3" json:"GPIOLineAlias,omitempty"`
}

func (x *GPIOselected) Reset() {
	*x = GPIOselected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPIOselected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPIOselected) ProtoMessage() {}

func (x *GPIOselected) ProtoReflect() protoreflect.Message {
	mi := &file_rio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPIOselected.ProtoReflect.Descriptor instead.
func (*GPIOselected) Descriptor() ([]byte, []int) {
	return file_rio_proto_rawDescGZIP(), []int{0}
}

func (x *GPIOselected) GetGPIOLineOffset() int32 {
	if x != nil {
		return x.GPIOLineOffset
	}
	return 0
}

func (x *GPIOselected) GetGPIOLineValue() int32 {
	if x != nil {
		return x.GPIOLineValue
	}
	return 0
}

func (x *GPIOselected) GetGPIOLineAlias() string {
	if x != nil {
		return x.GPIOLineAlias
	}
	return ""
}

type ServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseString string `protobuf:"bytes,1,opt,name=ResponseString,proto3" json:"ResponseString,omitempty"`
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_rio_proto_rawDescGZIP(), []int{1}
}

func (x *ServerResponse) GetResponseString() string {
	if x != nil {
		return x.ResponseString
	}
	return ""
}

var File_rio_proto protoreflect.FileDescriptor

var file_rio_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x69, 0x6f,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x47, 0x50, 0x49, 0x4f, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x47, 0x50, 0x49, 0x4f, 0x4c, 0x69,
	0x6e, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x47, 0x50, 0x49, 0x4f, 0x4c, 0x69, 0x6e, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x24,
	0x0a, 0x0d, 0x47, 0x50, 0x49, 0x4f, 0x4c, 0x69, 0x6e, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x47, 0x50, 0x49, 0x4f, 0x4c, 0x69, 0x6e, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x47, 0x50, 0x49, 0x4f, 0x4c, 0x69, 0x6e, 0x65,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x47, 0x50, 0x49,
	0x4f, 0x4c, 0x69, 0x6e, 0x65, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x32, 0x92, 0x01, 0x0a, 0x03, 0x52, 0x69, 0x6f, 0x12, 0x45, 0x0a, 0x0f,
	0x53, 0x65, 0x74, 0x47, 0x50, 0x49, 0x4f, 0x62, 0x79, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x16, 0x2e, 0x72, 0x69, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x50, 0x49, 0x4f, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x1a, 0x18, 0x2e, 0x72, 0x69, 0x6f, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x47, 0x50, 0x49, 0x4f, 0x62, 0x79,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x16, 0x2e, 0x72, 0x69, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x50, 0x49, 0x4f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x1a, 0x18, 0x2e,
	0x72, 0x69, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x72, 0x69, 0x6d, 0x65, 0x6c, 0x2d,
	0x30, 0x2f, 0x72, 0x69, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rio_proto_rawDescOnce sync.Once
	file_rio_proto_rawDescData = file_rio_proto_rawDesc
)

func file_rio_proto_rawDescGZIP() []byte {
	file_rio_proto_rawDescOnce.Do(func() {
		file_rio_proto_rawDescData = protoimpl.X.CompressGZIP(file_rio_proto_rawDescData)
	})
	return file_rio_proto_rawDescData
}

var file_rio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rio_proto_goTypes = []interface{}{
	(*GPIOselected)(nil),   // 0: rio_grpc.GPIOselected
	(*ServerResponse)(nil), // 1: rio_grpc.ServerResponse
}
var file_rio_proto_depIdxs = []int32{
	0, // 0: rio_grpc.Rio.SetGPIObyOffset:input_type -> rio_grpc.GPIOselected
	0, // 1: rio_grpc.Rio.SetGPIObyAlias:input_type -> rio_grpc.GPIOselected
	1, // 2: rio_grpc.Rio.SetGPIObyOffset:output_type -> rio_grpc.ServerResponse
	1, // 3: rio_grpc.Rio.SetGPIObyAlias:output_type -> rio_grpc.ServerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rio_proto_init() }
func file_rio_proto_init() {
	if File_rio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPIOselected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rio_proto_goTypes,
		DependencyIndexes: file_rio_proto_depIdxs,
		MessageInfos:      file_rio_proto_msgTypes,
	}.Build()
	File_rio_proto = out.File
	file_rio_proto_rawDesc = nil
	file_rio_proto_goTypes = nil
	file_rio_proto_depIdxs = nil
}
